# Generated by Django 5.1.2 on 2024-11-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek_coin', '0002_alter_transaction_receiver_alter_transaction_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histohy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
